#Higher Lower Game Data
data = [
    {
        "name" : "Instagram",
        "country" : "USA",
        "description" : "Social Media Platform",
        "followers" : 645,
    },
    {
        "name" : "Cristiano Ronaldo",
        "country" : "Portugal",
        "description" : "Footballer",
        "followers" : 595,
    },
    {
        "name" : "lionel Messi",
        "country" : "Argentina",
        "description" : "Footballer",
        "followers" : 478,
    },
    {
        "name" : "Selena Gomez",
        "country" : "USA",
        "description" : "Musician and Actress",
        "followers" : 425,
    },
    {
        "name" : "Kylie Jenner",
        "country" : "USA",
        "description" : "TV Personality and Businesswoman",
        "followers" : 395,
    },
    {
        "name" : "Dwayne Johnson",
        "country" : "USA",
        "description" : "Actor and Professional Wrestler",
        "followers" : 385,
    },
    {
        "name" : "Ariana Grande",
        "country" : "USA",
        "description" : "Musician and Actress",
        "followers" : 375,
    },
    {
        "name" : "Kim Kardashian",
        "country" : "USA",
        "description" : "TV Personality and Model and Businesswoman",
        "followers" : 360,
    },
    {
        "name" : "Beyone",
        "country" : "USA",
        "description" : "Musician",
        "followers" : 312,
    },
    {
        "name" : "Khloe Kardashian",
        "country" : "USA",
        "description" : "TV Personality and Model",
        "followers" : 309,
    },
    {
        "name" : "Nike",
        "country" : "USA",
        "description" : "Sportswear Brand",
        "followers" : 299,
    },
    {
        "name" : "Justin Bieber",
        "country" : "Canada",
        "description" : "Musician",
        "followers" : 292,
    },
    {
        "name" : "Kendall Jenner",
        "country" : "USA",
        "description" : "TV Personality and Model",
        "followers" : 291,
    },
    {
        "name" : "KNatonal Geographic",
        "country" : "USA",
        "description" : "Magazine",
        "followers" : 279,
    },
    {
        "name" : "Taylor Swift",
        "country" : "USA",
        "description" : "Musician",
        "followers" : 264,
    },
    {
        "name" : "Virat Kohli",
        "country" : "India",
        "description" : "Cricketer",
        "followers" : 252,
    },
    {
        "name" : "Jennifer Lopez",
        "country" : "USA",
        "description" : "Musician and Actress",
        "followers" : 248,
    },
    {
        "name" : "Kourtney Kardashian",
        "country" : "USA",
        "description" : "TV Personality and Model",
        "followers" : 222,
    },
    {
        "name" : "Nicki Minaj",
        "country" : "Trinidad & Tobago",
        "description" : "Musician",
        "followers" : 221,
    },
    {
        "name" : "Miley Cyrus",
        "country" : "USA",
        "description" : "Musician and Actress",
        "followers" : 211,
    },
    {
        "name" : "Neymar",
        "country" : "Brazil",
        "description" : "Footballer",
        "followers" : 209,
    },
    {
        "name" : "Katy Perry",
        "country" : "USA",
        "description" : "Musician",
        "followers" : 201,
    },
    {
        "name" : "Zendaya",
        "country" : "USA",
        "description" : "Actress and Musician",
        "followers" : 182,
    },
    {
        "name" : "Kevi Hart",
        "country" : "USA",
        "description" : "Comedian and Actor",
        "followers" : 176,
    },
    {
        "name" : "Cardi B",
        "country" : "USA",
        "description" : "Musician and Actress",
        "followers" : 166,
    },
    {
        "name" : "Demi Lovato",
        "country" : "USA",
        "description" : "Musician and Actress",
        "followers" : 156,
    },
    {
        "name" : "LeBron James",
        "country" : "USA",
        "description" : "Basketball Player",
        "followers" : 155,
    },
    {
        "name" : "Rihanna",
        "country" : "Barbados",
        "description" : "Musician",
        "followers" : 150,
    },
    {
        "name" : "Chris Brown",
        "country" : "USA",
        "description" : "Musician",
        "followers" : 141,
    },
    {
        "name" : "Real Madrid CF",
        "country" : "Spain",
        "description" : "Football Club",
        "followers" : 139,
    },
    {
        "name" : "Ellen DeGeneres",
        "country" : "USA",
        "description" : "Comedian and TV Personality",
        "followers" : 137,
    },
    {
        "name" : "Drake",
        "country" : "Canada",
        "description" : "Musician",
        "followers" : 139,
    },
    {
        "name" : "FC Barcelona",
        "country" : "Spain",
        "description" : "Football Club",
        "followers" : 121,
    },
    {
        "name" : "Billie Eilish",
        "country" : "USA",
        "description" : "Musician",
        "followers" : 109,
    },
    {
        "name" : "UEFA Champions League",
        "country" : "Europe",
        "description" : "Club Football Competition",
        "followers" : 105,
    },
    {
        "name" : "Kylian Mbappe",
        "country" : "France",
        "description" : "Footballer",
        "followers" : 104,
    },
    {
        "name" : "Gal Gadot",
        "country" : "Israel",
        "description" : "Actress",
        "followers" : 103,
    },
    {
        "name" : "Vin Diesel",
        "country" : "USA",
        "description" : "Actor",
        "followers" : 94.8,
    },
    {
        "name" : "NASA",
        "country" : "USA",
        "description" : "Space Agency",
        "followers" : 92.7,
    },
    {
        "name" : "Dua Lipa",
        "country" : "UK",
        "description" : "Musician",
        "followers" : 88.3,
    },
    {
        "name" : "Priyanka Chopra",
        "country" : "India",
        "description" : "Actress",
        "followers" : 87.6,
    },
    {
        "name" : "Shakira",
        "country" : "Colombia",
        "description" : "Musician",
        "followers" : 86.6,
    },
    {
        "name" : "NBA",
        "country" : "USA",
        "description" : "Professional Basketball League",
        "followers" : 80.9,
    },
    {
        "name" : "Shraddha Kapoor",
        "country" : "India",
        "description" : "Actress",
        "followers" : 80.8,
    },
    {
        "name" : "Snoop Dogg",
        "country" : "USA",
        "description" : "Musician",
        "followers" : 80,
    },
    {
        "name" : "David Beckham",
        "country" : "UK",
        "description" : "Former footballer and Owner of Inter Miami CF",
        "followers" : 79.3,
    },
    {
        "name" : "Khaby Lame",
        "country" : "Italy",
        "description" : "Social Media Personality",
        "followers" : 79.1,
    },
    {
        "name" : "Gigi Hadid",
        "country" : "USA",
        "description" : "Model",
        "followers" : 78.5,
    },
    {
        "name" : "Alia Bhatt",
        "country" : "India",
        "description" : "Actress",
        "followers" : 78.2,
    },
    {
        "name" : "Narendra Modi",
        "country" : "India",
        "description" : "Politician",
        "followers" : 76.5,
    },
]